/**
 * vuex store 全局 Mutation 事件类型常量
 * @type {string}
 */

//================================================================================//
// globalProperties 模块
//================================================================================//
export const SET_GLOBAL_PROPERTIES_SORT_VALUES = 'SET_GLOBAL_PROPERTIES_SORT_VALUES';
export const SET_GLOBAL_PROPERTIES_PLATFORM_LIST = 'SET_GLOBAL_PROPERTIES_PLATFORM_LIST';
export const SET_GLOBAL_PROPERTIES_TYPE_LIST = 'SET_GLOBAL_PROPERTIES_TYPE_LIST';
export const SET_GLOBAL_PROPERTIES_TYPE_CONTENT_LENGTH = 'SET_GLOBAL_PROPERTIES_TYPE_CONTENT_LENGTH';
export const SET_GLOBAL_PROPERTIES_MAX_OPINION_NUM = 'SET_GLOBAL_PROPERTIES_MAX_OPINION_NUM';


//================================================================================//
// userLogin 模块
//================================================================================//
export const GET_USER_LOGIN_DIALOG_VISIBLE = 'GET_USER_LOGIN_DIALOG_VISIBLE';
export const SET_USER_LOGIN_DIALOG_VISIBLE = 'SET_USER_LOGIN_DIALOG_VISIBLE';
export const SET_USER_LOGIN_DIALOG_TITLE = 'SET_USER_LOGIN_DIALOG_TITLE';
export const SET_USER_LOGIN_DIALOG_TYPE = 'SET_USER_LOGIN_DIALOG_TYPE';
export const SET_USER_LOGIN_INSTANCE = 'SET_USER_LOGIN_INSTANCE';
export const SET_USER_LOGIN_INSTANCE_USER_ID = 'SET_USER_LOGIN_INSTANCE_USER_ID';
export const SET_USER_LOGIN_INSTANCE_USER_NAME = 'SET_USER_LOGIN_INSTANCE_USER_NAME';
export const SET_USER_LOGIN_INSTANCE_PASSWORD = 'SET_USER_LOGIN_INSTANCE_PASSWORD';
export const SET_USER_LOGIN_INSTANCE_CODE = 'SET_USER_LOGIN_INSTANCE_CODE';
export const SET_USER_LOGIN_VIEW_ITEM = 'SET_USER_LOGIN_VIEW_ITEM';


//================================================================================//
// userFollowing 模块
//================================================================================//
export const SET_CHANGE_ADD_FOLLOWING_DIALOG_KEY = 'SET_CHANGE_ADD_FOLLOWING_DIALOG_KEY';
export const SET_USER_FOLLOWING_DIALOG_VISIBLE = 'SET_USER_FOLLOWING_DIALOG_VISIBLE';
export const SET_USER_FOLLOWING_DIALOG_TITLE = 'SET_USER_FOLLOWING_DIALOG_TITLE';
export const SET_USER_FOLLOWING_DIALOG_TYPE = 'SET_USER_FOLLOWING_DIALOG_TYPE';
export const SET_USER_FOLLOWING_IS_SHOW_FOLLOWING_TYPE = 'SET_USER_FOLLOWING_IS_SHOW_FOLLOWING_TYPE';
export const SET_USER_FOLLOWING_INSTANCE = 'SET_USER_FOLLOWING_INSTANCE';
export const SET_USER_FOLLOWING_INSTANCE_ID = 'SET_USER_FOLLOWING_INSTANCE_ID';
export const SET_USER_FOLLOWING_INSTANCE_USER_ID = 'SET_USER_FOLLOWING_INSTANCE_USER_ID';
export const SET_USER_FOLLOWING_INSTANCE_FOLLOWING_ID = 'SET_USER_FOLLOWING_INSTANCE_FOLLOWING_ID';
export const SET_USER_FOLLOWING_INSTANCE_PLATFORM_ID = 'SET_USER_FOLLOWING_INSTANCE_PLATFORM_ID';
export const SET_USER_FOLLOWING_INSTANCE_TYPE_ID = 'SET_USER_FOLLOWING_INSTANCE_TYPE_ID';
export const SET_USER_FOLLOWING_INSTANCE_USER_KEY = 'SET_USER_FOLLOWING_INSTANCE_USER_KEY';
export const SET_USER_FOLLOWING_INSTANCE_NAME = 'SET_USER_FOLLOWING_INSTANCE_NAME';
export const SET_USER_FOLLOWING_INSTANCE_MAIN_PAGE = 'SET_USER_FOLLOWING_INSTANCE_MAIN_PAGE';
export const SET_USER_FOLLOWING_INSTANCE_PROFILE_PHOTO = 'SET_USER_FOLLOWING_INSTANCE_PROFILE_PHOTO';
export const SET_USER_FOLLOWING_INSTANCE_SIGNATURE = 'SET_USER_FOLLOWING_INSTANCE_SIGNATURE';
export const SET_USER_FOLLOWING_INSTANCE_IS_USER = 'SET_USER_FOLLOWING_INSTANCE_IS_USER';
export const SET_USER_FOLLOWING_INSTANCE_SORT_NO = 'SET_USER_FOLLOWING_INSTANCE_SORT_NO';
export const SET_USER_FOLLOWING_INSTANCE_REMARK_LIST = 'SET_USER_FOLLOWING_INSTANCE_REMARK_LIST';
export const SET_USER_FOLLOWING_INSTANCE_REMARK_LIST_JSON = 'SET_USER_FOLLOWING_INSTANCE_REMARK_LIST_JSON';
export const SET_USER_FOLLOWING_VIEW_ITEM = 'SET_USER_FOLLOWING_VIEW_ITEM';


//================================================================================//
// userFollowingType 模块
//================================================================================//
export const SET_USER_FOLLOWING_TYPE_DIALOG_VISIBLE = 'SET_USER_FOLLOWING_TYPE_DIALOG_VISIBLE';
export const SET_USER_FOLLOWING_TYPE_DIALOG_TITLE = 'SET_USER_FOLLOWING_TYPE_DIALOG_TITLE';
export const SET_USER_FOLLOWING_TYPE_DIALOG_TYPE = 'SET_USER_FOLLOWING_TYPE_DIALOG_TYPE';
export const SET_USER_FOLLOWING_TYPE_INSTANCE = 'SET_USER_FOLLOWING_TYPE_INSTANCE';
export const SET_USER_FOLLOWING_TYPE_INSTANCE_ID = 'SET_USER_FOLLOWING_TYPE_INSTANCE_ID';
export const SET_USER_FOLLOWING_TYPE_INSTANCE_USER_ID = 'SET_USER_FOLLOWING_TYPE_INSTANCE_USER_ID';
export const SET_USER_FOLLOWING_TYPE_INSTANCE_PLATFORM_ID = 'SET_USER_FOLLOWING_TYPE_INSTANCE_PLATFORM_ID';
export const SET_USER_FOLLOWING_TYPE_INSTANCE_TYPE_NAME = 'SET_USER_FOLLOWING_TYPE_INSTANCE_TYPE_NAME';
export const SET_USER_FOLLOWING_TYPE_INSTANCE_SORT_NO = 'SET_USER_FOLLOWING_TYPE_INSTANCE_SORT_NO';
export const SET_USER_FOLLOWING_TYPE_VIEW_ITEM = 'SET_USER_FOLLOWING_TYPE_VIEW_ITEM';


//================================================================================//
// userFollowingRelation 模块
//================================================================================//
export const SET_USER_FOLLOWING_RELATION_DIALOG_VISIBLE = 'SET_USER_FOLLOWING_RELATION_DIALOG_VISIBLE';
export const SET_USER_FOLLOWING_RELATION_DIALOG_TITLE = 'SET_USER_FOLLOWING_RELATION_DIALOG_TITLE';
export const SET_USER_FOLLOWING_RELATION_DIALOG_TYPE = 'SET_USER_FOLLOWING_RELATION_DIALOG_TYPE';
export const SET_USER_FOLLOWING_RELATION_INSTANCE = 'SET_USER_FOLLOWING_RELATION_INSTANCE';
export const SET_USER_FOLLOWING_RELATION_INSTANCE_ID = 'SET_USER_FOLLOWING_RELATION_INSTANCE_ID';
export const SET_USER_FOLLOWING_RELATION_INSTANCE_USER_ID = 'SET_USER_FOLLOWING_RELATION_INSTANCE_USER_ID';
export const SET_USER_FOLLOWING_RELATION_INSTANCE_FOLLOWING_ID = 'SET_USER_FOLLOWING_RELATION_INSTANCE_FOLLOWING_ID';
export const SET_USER_FOLLOWING_RELATION_INSTANCE_PLATFORM_ID = 'SET_USER_FOLLOWING_RELATION_INSTANCE_PLATFORM_ID';
export const SET_USER_FOLLOWING_RELATION_INSTANCE_TYPE_ID = 'SET_USER_FOLLOWING_RELATION_INSTANCE_TYPE_ID';
export const SET_USER_FOLLOWING_RELATION_INSTANCE_SORT_NO = 'SET_USER_FOLLOWING_RELATION_INSTANCE_SORT_NO';
export const SET_USER_FOLLOWING_RELATION_VIEW_ITEM = 'SET_USER_FOLLOWING_RELATION_VIEW_ITEM';


//================================================================================//
// userOpinion 模块
//================================================================================//
export const SET_USER_OPINION_DIALOG_VISIBLE = 'SET_USER_OPINION_DIALOG_VISIBLE';
export const SET_USER_OPINION_DIALOG_TITLE = 'SET_USER_OPINION_DIALOG_TITLE';
export const SET_USER_OPINION_DIALOG_TYPE = 'SET_USER_OPINION_DIALOG_TYPE';
export const SET_USER_OPINION_INSTANCE = 'SET_USER_OPINION_INSTANCE';
export const SET_USER_OPINION_INSTANCE_ID = 'SET_USER_OPINION_INSTANCE_ID';
export const SET_USER_OPINION_INSTANCE_USER_ID = 'SET_USER_OPINION_INSTANCE_USER_ID';
export const SET_USER_OPINION_INSTANCE_PLATFORM_ID = 'SET_USER_OPINION_INSTANCE_PLATFORM_ID';
export const SET_USER_OPINION_INSTANCE_OPINION_TYPE = 'SET_USER_OPINION_INSTANCE_OPINION_TYPE';
export const SET_USER_OPINION_INSTANCE_OPINION_CONTENT = 'SET_USER_OPINION_INSTANCE_OPINION_CONTENT';
export const SET_USER_OPINION_INSTANCE_SORT_NO = 'SET_USER_OPINION_INSTANCE_SORT_NO';
export const SET_USER_OPINION_VIEW_ITEM = 'SET_USER_OPINION_VIEW_ITEM';
